import type { Metadata } from 'next';
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
} from '@clerk/nextjs';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="ja">
                <body className="bg-[#171717] text-[#F0F0F0]">
                    <SignedOut>
                        <SignInButton />
                    </SignedOut>
                    <SignedIn></SignedIn>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
